[book]
authors = ["twisterarmy"]
language = "en"
multilingual = false
src = "src"
title = "The twister P2P Book"

[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/twisterarmy/book"
git-repository-icon = "fa-github"
# edit-url-template = "https://github.com/twisterarmy/book/edit/main/{path}"

[preprocessor.alerts]
[preprocessor.preprocessor]
command = "python3 preprocessor.py"
